"""initial schema

Revision ID: 092dde544746
Revises: 
Create Date: 2026-09-03 16:57:15.587158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092dde544746'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_collection_name')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_user_id'), ['user_id'], unique=False)

    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_plans_user_id'), ['user_id'], unique=False)

    op.create_table('saved_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('cuisine', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'external_id', name='uq_user_recipe')
    )
    with op.batch_alter_table('saved_recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_recipes_user_id'), ['user_id'], unique=False)

    op.create_table('collection_recipes',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('saved_recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['saved_recipe_id'], ['saved_recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'saved_recipe_id')
    )
    op.create_table('meal_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.Column('saved_recipe_id', sa.Integer(), nullable=False),
    sa.Column('planned_for', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['saved_recipe_id'], ['saved_recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_plan_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_plan_items_meal_plan_id'), ['meal_plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plan_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_plan_items_meal_plan_id'))

    op.drop_table('meal_plan_items')
    op.drop_table('collection_recipes')
    with op.batch_alter_table('saved_recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_recipes_user_id'))

    op.drop_table('saved_recipes')
    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_plans_user_id'))

    op.drop_table('meal_plans')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_user_id'))

    op.drop_table('collections')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
